version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: ../Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    command: yarn dev

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm start
